### ISSUE TITLE
Unable to start mdns: Out of memory

### ISSUE THREAD

**Issue by Jejebond** [jippi/docker-ser2net#3]
Hi ! 

I've got an issue. The container won't launch. I've tried a lot of stuff. It stopted working on 04/25 around 6pm. Probably due to the update. The terminal says : 

`Unable to start mdns: Out of memory`

My Docker compose : 

```version: '3.8'
services:
  ser2net:
    container_name: ser2net
    image: ghcr.io/jippi/docker-ser2net
    restart: unless-stopped
    network_mode: host
    ports:
      - 20108:20108
    volumes:
      - /volume1/docker/ser2net/ser2net.yaml:/etc/ser2net/ser2net.yaml:ro
    devices:
      - /dev/ttyACM0
```

My ser2net.yaml file (used for Conbee2 dongle on Synology NAS with Home assistant) : 

```
connection: &con01
  accepter: tcp,20108
  connector: serialdev,/dev/ttyACM0,115200n81,nobreak,local
  options:
    kickolduser: true
```

Thanks

**Comment by jippi** [comment]
Can you replicate it with [any of the previous tags](https://github.com/jippi/docker-ser2net/pkgs/container/docker-ser2net)?

**Comment by Jejebond** [comment]
Thanks, you are right, it's not linked to latest tag. 4.6.1 has the same issue. Can't figure out how to fix this. Still, it used to work before. Can't see what has changed then...

#https://github.com/cminyard/ser2net/issues/63

Similar issue but -d parameter, as sugested, is already set.

**Comment by jippi** [comment]
Does it happen on [4.5.1](https://github.com/users/jippi/packages/container/docker-ser2net/154069781?tag=4.5.1) as well?

**Comment by Jejebond** [comment]
Same on [4.5.1](https://github.com/users/jippi/packages/container/docker-ser2net/154069781?tag=4.5.1)

`stderr | Unable to start mdns: Out of memory`

I was able to update multiple times. But this time... something changed with Portainer ? I'm a beginner at docker stuff.

**Comment by jippi** [comment]
I don't use Portainer, so can't speak to any changes within that ecosystem - does it work if you increase the memory limit for the Portainer container?

**Comment by jippi** [comment]
At a glance, it _might_ be an upstream issue in the `mdns` library - googling leads to multiple resources mirroring the experience described here: https://github.com/espressif/esp-idf/issues/13333

**Comment by jippi** [comment]
I don't think this is a `jippi/ser2net` or Docker issue; I can't reproduce it on my Raspberry PI, Mac, NAS, or home lab servers (across arm and amd64 architecture) - going to close the issue - but feel free to provide more info, debug info, etc. in here

**Comment by scyto** [comment]
I just pulled this container for the first time and hit the same issue on an rPi, happy to provide any details i can

```
version: '3.4'
services:
  ser2net:
    container_name: ser2net
    image: ghcr.io/jippi/docker-ser2net
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/pi/ser2net/data/ser2net.yaml:/etc/ser2net/ser2net.yaml
    devices:
      - /dev/ttyUSB1
```

yaml
```
%YAML 1.1
---

define: &banner Connected to port \N(\d)\r\n

default:
      name: local
      value: true
      class: serialdev

connection: &my-console
      accepter: tcp,8000
      connector: serialdev,/dev/ttyUSB0,460800N81
      options:
              banner: *banner
```

log

```
Unable to start mdns: Out of memory
```

given i don't need mdns for my application can i disable that in someway?


---edit---
oh its a non critical error, the ser2net functionality still works, confusing but ok :-)
